defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
    
args:
    model_name: 'deeponet'
    if_training: True
    continue_training: False
    num_workers: 2
    batch_size: 20
    initial_step: 1
    t_train: 101
    model_update: 10
    filename: '2D_diff-react_NA_NA'
    single_file: True
    reduced_resolution: 1
    reduced_resolution_t: 1
    reduced_batch: 1
    epochs: 100
    learning_rate: 1.e-3
    scheduler_step: 10
    scheduler_gamma: 0.8
    base_path: '../data_download/data/1D/Advection/Train/'
    # IFNO
    num_channels: 1
    modes: 12
    width: 20
    #Unet
    in_channels: 2
    out_channels: 2
    ar_mode: True
    pushforward: True
    unroll_step: 20


    #Inverse
    training_type: autoregressive
    #Inverse MCMC
    mcmc_num_samples: 20
    mcmc_warmup_steps: 10
    mcmc_num_chains: 1
    num_samples_max: 1000
    in_channels_hid: 64
    inverse_model_type: InitialConditionInterp    
    #Inverse grad
    inverse_epochs: 100
    inverse_learning_rate: 0.2
    inverse_verbose_flag: False
    #Plotting
    plot: False
    channel_plot: 0 # Which channel/variable to be plotted
    x_min: -1
    x_max: 1
    y_min: -1
    y_max: 1
    t_min: 0
    t_max: 5